export const Teamdetails = [
  {
    id: 1,
    src: "/img/our-team/uploads/bhaveshbahi.jpeg",
    teamtitle: "Bhavesh G",
    teamsubtitle: "Lead - App Team",
    linkedin: "https://in.linkedin.com/in/bhavesh-gohil-93b6a1189",
    twitter: "",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 2,
    src: "/img/our-team/uploads/mehul.png",
    teamtitle: "Mehul C",
    teamsubtitle: "Application developer",
    linkedin: "",
    twitter: "",
    // linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 3,
    src: "/img/our-team/uploads/ravibahi.png",
    teamtitle: "Ravi G",
    teamsubtitle: "Frontend developer",
    linkedin: "https://in.linkedin.com/in/ravi-gediya-414086231",
    twitter: "",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 4,
    src: "/img/our-team/uploads/dhruvi.png",
    teamtitle: "Dhruvi P",
    teamsubtitle: "Lead UI/UX Team",
    linkedin: "",
    twitter: "",
    // linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 5,
    src: "/img/our-team/uploads/rohan.png",
    teamtitle: "Rohan V",
    teamsubtitle: "Nodejs developer",
    linkedin: "https://www.linkedin.com/in/rohan-vaghasiya-13465b219/",
    twitter: "",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 6,
    src: "/img/our-team/uploads/parin.jpeg",
    teamtitle: "Parin S",
    teamsubtitle: "Nodejs developer",
    linkedin: "https://www.linkedin.com/in/parinsuvagiya/",
    twitter: "",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 7,
    src: "/img/our-team/uploads/don.png",
    teamtitle: "Dharmik D",
    teamsubtitle: "React developer",
    linkedin: "https://in.linkedin.com/in/dayanidharmik",
    twitter: "https://twitter.com/dayani9912",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 8,
    src: "/img/our-team/uploads/shreya.png",
    teamtitle: "Shreya G",
    teamsubtitle: "UI/UX designer",
    linkedin: "https://www.linkedin.com/in/shreya-gujarati-b112b6190",
    twitter: "",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 9,
    src: "/img/our-team/uploads/paraful.png",
    teamtitle: "Praful C",
    teamsubtitle: "Application developer",
    linkedin: "",
    twitter: "",
    // linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 10,
    src: "/img/our-team/uploads/levis.jpeg",
    teamtitle: "Levis P",
    teamsubtitle: "Blockchain developer",
    linkedin: "https://in.linkedin.com/in/levispanseriya",
    twitter: "https://twitter.com/LevisPanseriya/",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 11,
    src: "/img/our-team/uploads/yagnik.jpeg",
    teamtitle: "Yagnik V",
    teamsubtitle: "React developer",
    linkedin: "https://www.linkedin.com/in/yagnik-vadadoriya-98991b243/",
    twitter: "",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    // twitter_img: "../../img/our-team/twitter-small.png",
  },
  {
    id: 12,
    src: "/img/our-team/uploads/ravi.jpeg",
    teamtitle: "Ravi Sanghani",
    teamsubtitle: "Blockchain developer",
    linkedin: "https://www.linkedin.com/in/ravi-sanghani",
    twitter: "https://twitter.com/ethravi",
    linkedin_img: "../../img/our-team/linkedin-small.png",
    twitter_img: "../../img/our-team/twitter-small.png",
  },
];
