export const RolesDetails = [

    {
        id:1,
        TeamMembers:"1,00,00,000 onwards",
        Supremacy:"Emperor",
    },
    {
        id:2,
        TeamMembers:"10,00,000-99,99,999",
        Supremacy:"Queen",
    },
    {
        id:3,
        TeamMembers:"1,00,000-9,99,999",
        Supremacy:"King",
    },
    {
        id:4,
        TeamMembers:"10,000-99,999",
        Supremacy:"Princess",
    },
    {
        id:5,
        TeamMembers:"1,000-9,999",
        Supremacy:"Prince",
    },
    {
        id:6,
        TeamMembers:"100-999",
        Supremacy:"Rook",
    },
    {
        id:7,
        TeamMembers:"10-99",
        Supremacy:"Bishop",
    },
    {
        id:8,
        TeamMembers:"1-9",
        Supremacy:"Knight",
    },
    {
        id:9,
        TeamMembers:"0",
        Supremacy:"Soldier",
    },

];
